Mongoid::Extensions::String::Inflections::CHAR_CONV.merge({
  " " => "-",
  "\"" => "-quot-",
  "#" => "-hash-",
  "%" => "-perc-",
  "&" => "-and-",
  "/" => "-slash-",
  ":" => "-colon-",
  ";" => "-semicol-",
  "<" => "-lt-",
  "=" => "-eq-",
  ">" => "-gt-",
  "?" => "-ques-",
  "@" => "-at-",
  "[" => "-obrck-",
  "\\" => "-bckslsh-",
  "]" => "-clbrck-",
  "^" => "-carat-",
  "`" => "-bcktick-",
  "{" => "-lcurly-",
  "|" => "-pipe-",
  "}" => "-rcurly-",
  "~" => "-tilde-"})
