default: -r features/support/env.rb -r features/support/plain.rb -r features/support/paths.rb -r features/support/selectors.rb -r features/step_definitions features/plain
selenium: -r features/support/env.rb -r features/support/enhanced.rb  -r features/support/paths.rb -r features/support/selectors.rb -r   features/step_definitions features/enhanced

